# Pre-commit hooks for InfOCF
# Run: pre-commit install (one time setup)
# Run: pre-commit run --all-files (to run on all files)

repos:
  # Ruff - Ultra-fast Python linter and formatter (version synced with pyproject.toml)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2  # Keep in sync with pyproject.toml ruff version
    hooks:
      # Run the linter
      - id: ruff
        name: Ruff Linting
        args: [--fix]  # Automatically fix issues where possible
      # Run the formatter
      - id: ruff-format
        name: Ruff Formatting

  # Built-in hooks for common issues
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        name: Remove trailing whitespace
      - id: end-of-file-fixer
        name: Fix end of files
      - id: check-yaml
        name: Check YAML syntax
      - id: check-toml
        name: Check TOML syntax
      - id: check-json
        name: Check JSON syntax
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-added-large-files
        name: Check for large files
        args: ['--maxkb=1000']
      - id: mixed-line-ending
        name: Fix mixed line endings
        args: ['--fix=lf']

  # MyPy for type checking (optional, non-blocking)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        name: MyPy type checking (optional)
        additional_dependencies: [pysmt, numpy, pandas]
        args: [--ignore-missing-imports, --no-strict-optional]
        # Make it non-blocking - continue even if it fails
        stages: [manual]  # Only run when explicitly called

  # Security linting tools
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        name: Bandit security linting
        args: ['--format', 'custom', '-s', 'B101,B601,B301,B403']
        exclude: 'unittests/.*'  # Skip test files

  # pip-audit for dependency vulnerability scanning
  - repo: https://github.com/pypa/pip-audit
    rev: v2.9.0
    hooks:
      - id: pip-audit
        name: pip-audit (dependency vulnerability scan)
        args: ['--desc']
        additional_dependencies: ['pip>=25.2']
        # Temporarily non-blocking until pip 25.3 is released (GHSA-4xh5-x5gv-qwph)
        stages: [manual]  # Only run when explicitly called with: pre-commit run pip-audit

  # Additional optional hooks (run manually)
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        name: Docstring style checking
        args: ['--convention=numpy']
        stages: [manual]  # Only run when explicitly called
        exclude: 'parser/CKB.*\.py$'
