signature
gqhsco,pvsric,afoigf,vkisva,awzlel,dntatb,mctsjl,zmbtlx,zzycyw,dcfmkg,jecvoi,cqqfjt,vdzfpe,jwgxyn,mfviul,arxzwc,lisxmn,aovadb,ymahpn,gvdjrc
conditionals
randomTest_20_20_8 {
((((((mfviul;dntatb),mctsjl);arxzwc);(zmbtlx,vdzfpe)),jecvoi)|(aovadb;gvdjrc)),
(arxzwc|((lisxmn;afoigf);(vkisva,jecvoi))),
((cqqfjt;mfviul)|(pvsric,afoigf)),
(vdzfpe|(((!jwgxyn);(ymahpn;((!jecvoi);(gqhsco;mctsjl)))),(!(lisxmn;zmbtlx)))),
(lisxmn|(vdzfpe,(mctsjl;(afoigf;zmbtlx)))),
((pvsric;(jwgxyn,afoigf))|((aovadb;(zmbtlx;(mfviul;mctsjl))),dntatb)),
(((pvsric;vdzfpe);((vkisva,gvdjrc);arxzwc))|gqhsco),
(mfviul|((!((!(arxzwc;((((!gvdjrc);zmbtlx),pvsric),dcfmkg))),(!zzycyw)));(!(!(!(jwgxyn;ymahpn)))))),
((gqhsco,vdzfpe)|((((arxzwc,dntatb);gvdjrc);(dcfmkg;jwgxyn));(zmbtlx,(cqqfjt,mctsjl)))),
((lisxmn;jecvoi)|((ymahpn;vkisva);zmbtlx)),
(((jecvoi;pvsric);(!vkisva))|(((!gqhsco),(!dcfmkg)),vdzfpe)),
(((vkisva,aovadb);afoigf)|((!(!jwgxyn)),lisxmn)),
((awzlel,((((jwgxyn;gqhsco);vdzfpe);(!zzycyw)),arxzwc))|zmbtlx),
((mctsjl;dcfmkg)|(dntatb;mfviul)),
((lisxmn,(jecvoi,dcfmkg))|jwgxyn),
((ymahpn,((!awzlel),gqhsco))|((!(!(!(jecvoi;pvsric)))),(vdzfpe,(cqqfjt,jwgxyn)))),
((((ymahpn;gqhsco);zmbtlx),(!((!afoigf),vdzfpe)))|arxzwc),
(((zzycyw,arxzwc),(!dcfmkg))|(aovadb,dntatb)),
((vkisva;(mctsjl;(dcfmkg,vdzfpe)))|((!(!aovadb)),mfviul)),
(((gqhsco,pvsric),(!(!afoigf)))|vkisva)
}
