signature
betmdk,ozslgt,zirkws,msaasi,ntqevi,fvvkot,dgvzpo,izzdch,swkbwm,vgndlt,wwkzld,ojfyqj,wiwwmj,imbcbo,elhnqr,cvihgc,nfpxcg,bwvipg,zcbwnf,hzzcxh
conditionals
randomTest_20_20_72 {
(((!((hzzcxh;msaasi);ojfyqj));((!zcbwnf);(betmdk,ozslgt)))|(cvihgc,elhnqr)),
((((ntqevi;imbcbo),elhnqr);(!swkbwm))|((!((fvvkot,ojfyqj);wiwwmj)),zirkws)),
((ozslgt,ntqevi)|(((msaasi;(cvihgc;vgndlt));betmdk);((!bwvipg);(!fvvkot)))),
((msaasi,((cvihgc;hzzcxh),ojfyqj))|(fvvkot,(elhnqr,dgvzpo))),
(msaasi|((wiwwmj;zirkws),dgvzpo)),
((wiwwmj;(betmdk,izzdch))|((cvihgc,hzzcxh),(!((!(!(bwvipg,zcbwnf)));(!ojfyqj))))),
(((izzdch,(ntqevi,betmdk));((!imbcbo),(ojfyqj,cvihgc)))|((!(!(!hzzcxh)));((!(!(!swkbwm))),nfpxcg))),
((wwkzld,(wiwwmj,(nfpxcg;(!ntqevi))))|(((hzzcxh;zirkws);(!(cvihgc,fvvkot)));(!swkbwm))),
((((!swkbwm),(!msaasi));((!(!ozslgt));vgndlt))|((((wwkzld,dgvzpo),cvihgc);bwvipg),(!(nfpxcg;elhnqr)))),
((((hzzcxh,ojfyqj),cvihgc);(wwkzld,(!msaasi)))|(zcbwnf,ozslgt)),
(((!(!(!(izzdch;imbcbo)))),(!(!(!wwkzld))))|((!((!nfpxcg),(hzzcxh;swkbwm)));(!(msaasi,ozslgt)))),
((elhnqr;(!hzzcxh))|((!ojfyqj);((!zcbwnf),vgndlt))),
(ojfyqj|((ozslgt,(!hzzcxh));(msaasi;cvihgc))),
(hzzcxh|((!(((!swkbwm),ntqevi),msaasi)),bwvipg)),
((dgvzpo,(!(((!ojfyqj),ozslgt);(!vgndlt))))|((msaasi,bwvipg);(wwkzld,zcbwnf))),
(((wwkzld,fvvkot);(!ntqevi))|((ozslgt;msaasi),hzzcxh)),
((ntqevi,betmdk)|((cvihgc,swkbwm),(hzzcxh;(!msaasi)))),
(((!(nfpxcg,vgndlt)),swkbwm)|betmdk),
((ntqevi;(msaasi;ozslgt))|((!(hzzcxh;wwkzld)),(!(imbcbo;vgndlt)))),
((((((!ozslgt),(dgvzpo,(ntqevi,msaasi))),izzdch),betmdk),fvvkot)|zirkws)
}
