signature
wvxtnt,hdgonf,fvphbo,treekr,uaovnt,zttzgj,bghqia,jjocay,zzbevf,xkqidn,plzvjx,tdnkvp,lgzhdu,uuyesv,nxiadf,kczezm,rstdii,ptfbpt,pdylvn,zafxpp
conditionals
randomTest_20_20_5 {
(tdnkvp|((bghqia,(((!jjocay);fvphbo),ptfbpt)),(zttzgj,wvxtnt))),
(zttzgj|((!(plzvjx,treekr));(((((kczezm,tdnkvp),bghqia),(!uaovnt)),hdgonf);(!jjocay)))),
((((!(fvphbo;zafxpp));(!tdnkvp)),rstdii)|(lgzhdu,plzvjx)),
(((!hdgonf),lgzhdu)|(zttzgj;(nxiadf;bghqia))),
((((plzvjx;kczezm),rstdii),(!(!((pdylvn,zzbevf);((!lgzhdu);uuyesv)))))|(bghqia;(zafxpp,hdgonf))),
((hdgonf;rstdii)|((!(!(!bghqia))),((!((!wvxtnt);zttzgj)),((!plzvjx);((pdylvn,zafxpp),(uaovnt,zzbevf)))))),
((bghqia;zzbevf)|(uuyesv,rstdii)),
((((lgzhdu;(!zttzgj));tdnkvp);(!wvxtnt))|(xkqidn,(!(hdgonf,kczezm)))),
((((uuyesv;fvphbo),hdgonf);((!bghqia),(!(!(!((xkqidn;nxiadf);zafxpp))))))|(ptfbpt;rstdii)),
(treekr|((!((lgzhdu,ptfbpt),xkqidn)),((!zzbevf);((!wvxtnt);hdgonf)))),
(pdylvn|((nxiadf,(zzbevf,jjocay)),(((!bghqia),(xkqidn,zafxpp));uuyesv))),
(((!jjocay),(!kczezm))|((bghqia;(lgzhdu;(!uuyesv))),uaovnt)),
((treekr,fvphbo)|(((zttzgj;xkqidn),ptfbpt),((!jjocay);zzbevf))),
((((ptfbpt,tdnkvp),lgzhdu),(!(!treekr)))|jjocay),
((((!(rstdii;(ptfbpt,(tdnkvp;hdgonf))));zafxpp),(kczezm;nxiadf))|lgzhdu),
(((!jjocay),(!(tdnkvp,uuyesv)))|((((!nxiadf),(zafxpp,zttzgj)),plzvjx);(!kczezm))),
(((jjocay;(!rstdii)),uaovnt)|(((!(!uuyesv)),lgzhdu),(zzbevf,(bghqia;fvphbo)))),
(((!uuyesv),(!(!jjocay)))|(xkqidn;tdnkvp)),
(fvphbo|(((!((lgzhdu,rstdii);kczezm));uuyesv),(((!zzbevf);ptfbpt),plzvjx))),
(fvphbo|(uaovnt,(!(((!((!wvxtnt),(hdgonf,bghqia))),zttzgj);treekr))))
}
