signature
vgarts,cdsdxg,htbdxz,yugfkh,wfypmm,xcgwkn,oanzto,hxapvy,zfqhzz,tmyclm,stvmpj,zartya,ylrkwp,dnzdgs,wybrzz,axjboc
conditionals
randomTest_16_16_80 {
((tmyclm,(!(wybrzz;dnzdgs)))|((!((!zfqhzz),stvmpj)),(!wfypmm))),
(stvmpj|(((axjboc,(tmyclm,wybrzz)),(!(dnzdgs;(!zartya))));(zfqhzz,(!wfypmm)))),
((yugfkh,wfypmm)|(((!(!((wybrzz,zfqhzz),(!vgarts)))),(xcgwkn;(!htbdxz)));(!(!(stvmpj;hxapvy))))),
(tmyclm|((htbdxz,zartya);wfypmm)),
(((!(!(!yugfkh))),(wybrzz,(tmyclm;((!ylrkwp),wfypmm))))|xcgwkn),
((((ylrkwp;zfqhzz);vgarts);((!wfypmm);(!(!(!(dnzdgs;htbdxz))))))|(zartya,yugfkh)),
((((!yugfkh),(zfqhzz;hxapvy)),(axjboc;zartya))|(vgarts;(!xcgwkn))),
((((!(!(!zartya)));tmyclm);((xcgwkn,(zfqhzz;cdsdxg)),((!ylrkwp);oanzto)))|axjboc),
(((!(((!(!(!yugfkh)));xcgwkn),(!(htbdxz;(!vgarts)))));((!(!axjboc)),stvmpj))|hxapvy),
((tmyclm,(!(dnzdgs;ylrkwp)))|(wfypmm;(zfqhzz;wybrzz))),
((cdsdxg;zfqhzz)|(((!(!zartya)),(!yugfkh)),(((hxapvy,axjboc),wybrzz),(oanzto;vgarts)))),
(cdsdxg|((zartya,((ylrkwp;((wybrzz;hxapvy);oanzto));(stvmpj;axjboc))),htbdxz)),
(wybrzz|((stvmpj;(htbdxz,(vgarts;hxapvy)));(((!xcgwkn),oanzto),(wfypmm,zfqhzz)))),
(zfqhzz|(xcgwkn;(wfypmm,tmyclm))),
((((!oanzto);(wfypmm,(dnzdgs;yugfkh))),(!((ylrkwp,zartya),(wybrzz;hxapvy))))|zfqhzz),
(((!yugfkh);(!(cdsdxg,(htbdxz,wfypmm))))|vgarts)
}
