signature
yumlnu,crxrrg,fjmzrs,eukqte,ttnffe,jbxfve,phgusm,uzlhcm,awxpia,ikcrfe,lcfysb,fpjeva,meuybg,fkcyoo,gbnnrl,wmjrrf,qdwwjc,xbpaft,yxjies,dpunay
conditionals
randomTest_20_20_28 {
(((!yumlnu);(fkcyoo,(yxjies;xbpaft)))|(awxpia,fpjeva)),
(((gbnnrl,fkcyoo),(phgusm,uzlhcm))|(((ttnffe;wmjrrf);(!crxrrg));lcfysb)),
(((wmjrrf;jbxfve);(!eukqte))|(crxrrg;(!qdwwjc))),
((fkcyoo;(xbpaft;uzlhcm))|(yumlnu;eukqte)),
((fpjeva,meuybg)|((gbnnrl,(!(((!jbxfve),eukqte);yumlnu))),(((phgusm,(!awxpia)),qdwwjc);(!uzlhcm)))),
(((!(eukqte,qdwwjc)),((((lcfysb;ttnffe),dpunay);(!crxrrg));(!fpjeva)))|awxpia),
(((!(!((fjmzrs;jbxfve),(ikcrfe,(crxrrg;meuybg)))));(qdwwjc;fkcyoo))|((!awxpia),gbnnrl)),
((((fpjeva;fkcyoo),((uzlhcm,jbxfve);meuybg));(!phgusm))|(crxrrg;lcfysb)),
(((!wmjrrf);((fkcyoo,(lcfysb,crxrrg)),(xbpaft;(gbnnrl;fpjeva))))|(yxjies;eukqte)),
((fkcyoo,(fpjeva;ttnffe))|(wmjrrf,uzlhcm)),
(((wmjrrf;(dpunay,(!xbpaft))),(ttnffe,uzlhcm))|((fpjeva;ikcrfe);(crxrrg;lcfysb))),
(((!gbnnrl);(ttnffe;((!dpunay);(phgusm;meuybg))))|((!((!fkcyoo);(xbpaft,uzlhcm)));(!(eukqte;fpjeva)))),
((((!jbxfve);(qdwwjc;yxjies));(!fpjeva))|fjmzrs),
(fkcyoo|((yumlnu;(lcfysb,eukqte));qdwwjc)),
(meuybg|((ikcrfe;(!yumlnu));awxpia)),
((qdwwjc,(!(phgusm,(!jbxfve))))|((yxjies,meuybg),((!ttnffe),(fpjeva;ikcrfe)))),
(((qdwwjc,(ttnffe;(!(!dpunay))));(uzlhcm;lcfysb))|awxpia),
(((fkcyoo;(lcfysb;meuybg)),(gbnnrl;ikcrfe))|((!(!(xbpaft;dpunay))),jbxfve)),
((xbpaft;yxjies)|((!(!(uzlhcm;fjmzrs)));((fpjeva,((!(!ikcrfe)),((!yumlnu);(!fkcyoo)))),(gbnnrl,ttnffe)))),
((((!yumlnu);eukqte);fjmzrs)|(crxrrg;ttnffe))
}
