signature
evfipx,cggucd,uhrvfk,tdjtcz,ihrlts,rqpqbh,kfljtn,gmxrmt,kbftuz,jdoorx,stwved,lnutmm,casbxo,lcdcgu,fnhihs,enbkih,qehqng,uulfti,izncco,rpcqll
conditionals
randomTest_20_20_6 {
((((ihrlts;jdoorx),kfljtn);(!((tdjtcz,rpcqll),(!kbftuz))))|(evfipx,gmxrmt)),
(uhrvfk|((gmxrmt;rqpqbh);fnhihs)),
((stwved,((((rpcqll,uhrvfk);(!jdoorx));casbxo),((!(!fnhihs));kbftuz)))|(izncco,kfljtn)),
(((qehqng,((lcdcgu;izncco),lnutmm)),((((!stwved);enbkih),ihrlts),(!(tdjtcz;casbxo))))|uhrvfk),
(((!cggucd),(!(stwved;(tdjtcz;ihrlts))))|(((kfljtn,jdoorx),(fnhihs,(!evfipx)));qehqng)),
(((evfipx;gmxrmt);(ihrlts;(lcdcgu,(!((uhrvfk,izncco);(!fnhihs))))))|(qehqng,rqpqbh)),
((stwved,(izncco;(qehqng,kfljtn)))|(lcdcgu,(casbxo;evfipx))),
(((fnhihs,(!cggucd)),(lcdcgu;((stwved,kfljtn);uulfti)))|(enbkih,tdjtcz)),
(((!kbftuz);(!kfljtn))|(rpcqll,rqpqbh)),
(((!(!((izncco,(tdjtcz;(!rqpqbh)));casbxo)));(lnutmm;((qehqng;uulfti);(!cggucd))))|(fnhihs;(!enbkih))),
((kbftuz,(!jdoorx))|(fnhihs;(lnutmm;stwved))),
((izncco,stwved)|(rqpqbh;lcdcgu)),
(((!qehqng);((uulfti;tdjtcz);(!(!(stwved,uhrvfk)))))|(((cggucd;izncco),rpcqll),(!kfljtn))),
(casbxo|(((!(gmxrmt;evfipx));(!(lnutmm;lcdcgu))),(((!jdoorx);tdjtcz);(qehqng,kbftuz)))),
(((!uulfti);((fnhihs,cggucd);(qehqng;(!(!kbftuz)))))|((tdjtcz,(!uhrvfk));casbxo)),
(cggucd|(((!(!rpcqll)),(rqpqbh;(((!(enbkih,kfljtn));(!((!uhrvfk),izncco)));(!ihrlts))));(!(!(!lnutmm))))),
(((!(!stwved)),(enbkih,(lnutmm;gmxrmt)))|((lcdcgu,(kbftuz,(evfipx,uulfti))),(!((!cggucd),casbxo)))),
(((!(uulfti;rqpqbh));jdoorx)|((fnhihs,(cggucd,lcdcgu)),(!tdjtcz))),
((tdjtcz;kfljtn)|(enbkih,rpcqll)),
(((tdjtcz;uhrvfk),evfipx)|cggucd)
}
