name: Build and Release Wheels

on:
  push:
    tags: [ "v*" ]

jobs:
  build-release:
    runs-on: ubuntu-latest
    name: Build sdist and wheel, attach to GitHub Release

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.12

    - name: Install build tooling
      run: uv pip install build

    - name: Extract version from pyproject.toml
      id: extract_version
      run: |
        python - <<'PY' > .version
        import tomllib
        print(tomllib.load(open('pyproject.toml','rb'))['project']['version'])
        PY
        echo "version=$(cat .version)" >> $GITHUB_OUTPUT

    - name: Validate tag matches pyproject version
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "Tag: ${GITHUB_REF_NAME} / Version: v${{ steps.extract_version.outputs.version }}"
        if [ "v${{ steps.extract_version.outputs.version }}" != "${GITHUB_REF_NAME}" ]; then
          echo "Tag (=${GITHUB_REF_NAME}) does not match pyproject version (v${{ steps.extract_version.outputs.version }})." >&2
          exit 1
        fi

    - name: Build distributions (sdist and wheel)
      run: uv run python -m build

    - name: Create GitHub Release and upload artifacts
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
        name: infocf v${{ steps.extract_version.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
